name: test de commande
on:
  pull_request:
    branches: [ main ]

  Run-on-Windows:
    name: Run Test on Windows
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: print my name
        shell: pwsh
        run: echo Hector
